Additional x64 support for complete build.
x64 now builds completely using the Makefile-based build system. Most of
it was simply filling out EFI functionality. I haven't yet fixed up the
mingen-based build, and haven't yet removed the install.ck crutches for
x64. That will be up next.

This change needs the corresponding third-party fix that turns on softfp
for long doubles. If you're seeing libgcc_s.so.1: undefined reference to
__eqtf2 and friends, you need to rebuild GCC.